#!/bin/bash

light="#B2001D"
mid="#860016"
dark="#590815"

finalPoint=30000
deltaRotation=90

plot=""
plot=${plot}"'trajectory1.dat' u 2:3:4:1 every 10::0::${finalPoint} with lines lt 1 lw 6 palette notitle,"
plot=${plot}"'trajectory1.dat' u 2:3:4:1 every ::${finalPoint}::${finalPoint} with points pt 7 ps 1 palette notitle,"

if [ $finalPoint -gt 1000 ]; then
let final=finalPoint-1000
  plot=${plot}"'trajectory2.dat' u 2:3:4:1 every 10::0::${final} with lines lt 1 lw 6 palette notitle,"
  plot=${plot}"'trajectory2.dat' u 2:3:4:1 every ::${final}::${final} with points pt 7 ps 1 palette notitle,"
fi

if [ $finalPoint -gt 2000 ]; then
let final=finalPoint-2000
  plot=${plot}"'trajectory3.dat' u 2:3:4:1 every 10::0::${final} with lines lt 1 lw 6 palette notitle,"
  plot=${plot}"'trajectory3.dat' u 2:3:4:1 every ::${final}::${final} with points pt 7 ps 1 palette notitle,"
fi

gnuplot << END

set terminal eps enhanced color size 12, 4
set output "wide_ensemble.eps"

set border 0
set ticslevel 0

set lmargin screen 0
set rmargin screen 1
set bmargin screen 0.05
set tmargin screen 0.95

unset xtics
set format x ''
set xrange[-1.2:1.0]

unset ytics
set format y ''
set yrange[-1.2:1.0]

unset ztics
set format z ''
set zrange[-1.5:1.3]

unset colorbox
set palette rgbformulae 8, 9, 9 negative

set view 65, 30 + 1.8 * $deltaRotation, 1, 1

splot ${plot}

END
